#!/bin/ksh

sass --style expanded --line-numbers --load-path govuk_frontend_toolkit/stylesheets main.scss main.css
#sass --style compressed --load-path govuk_frontend_toolkit/stylesheets input.scss output.css


