#!/bin/ksh

./index.py

#rvm use ruby-1.9.3-p392
sass --style expanded --line-numbers --load-path govuk_frontend_toolkit/stylesheets stylesheets/survey.scss stylesheets/survey.css
#sass --style compressed --load-path govuk_frontend_toolkit/stylesheets input.scss output.css


